# Generated by Django 2.2.4 on 2019-08-23 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_system', '0002_auto_20190821_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficconditionlog',
            name='Processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trafficconditionlog',
            name='Solved',
            field=models.BooleanField(default=False),
        ),
    ]
