# Generated by Django 2.2.4 on 2019-08-29 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambulance_system', '0003_auto_20190823_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trafficconditionlog',
            name='Monitor',
        ),
        migrations.AddField(
            model_name='trafficconditionlog',
            name='Location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ambulance_system.Location'),
            preserve_default=False,
        ),
    ]
